spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.110.32.148:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
      username: root
      password: 123456ln
      # 下面为连接池的补充设置，应用到上面所有数据源中
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      time-between-eviction-runs-millis: 5000
  # Redis 配置
  redis:
    host: 47.110.32.148
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456ln
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 30000
# PageHelper分页插件
pagehelper:
  helperDialect: Mysql
  # 3.3.0版本可用 - 分页参数合理化，默认false禁用 ;启用时，pageNum < 1 会查询第一页，pageNum > pages会查询最后一页 ; 禁用时，pageNum < 1 或 pageNum > pages会返回空数据
  reasonable: true
  #自动根据参数分页配置
  supportMethodsArguments: true
  params: count=countSql
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.yjh.web.admin.domain
  global-config:
    id-type: 0
    field-strategy: 2
    capital-mode: true
    refresh-mapper: true

logging:
  level:
    root: info
    com.lrm: info
  file: log/blog.log
server:
  port: 8090



