spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.32.148:3306/blog
    username: root
    password: 123456ln
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: error
    com.lrm: error
  file: log/blog.log
server:
  port: 8090


